# Generated by Django 4.0.6 on 2022-10-13 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tyres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Таблица продаж')),
            ],
        ),
        migrations.CreateModel(
            name='Tyre_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_sales', to='sales.salestable', verbose_name='Таблица')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyr_sales', to='tyres.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sales', models.DateField(blank=True, verbose_name='дата реализации')),
                ('sales_value', models.IntegerField(blank=True, verbose_name='объем продаж контрагенту')),
                ('contragent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contragent_sales', to='dictionaries.contragentsmodel')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_table', to='sales.salestable', verbose_name='Таблица')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tyres.tyre')),
            ],
        ),
    ]
