# Generated by Django 4.0.6 on 2022-09-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sales', models.DateField(blank=True, verbose_name='дата реализации')),
                ('sales_value', models.IntegerField(blank=True, verbose_name='объем продаж контрагенту')),
                ('contragent', models.CharField(max_length=10, verbose_name='контрагент')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='tyres.tyre')),
            ],
        ),
    ]
