# Generated by Django 4.0.6 on 2022-09-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyr_sales', to='tyres.tyre')),
            ],
        ),
    ]
