# Generated by Django 4.0.6 on 2022-09-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_tyre_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre_sale',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_sales', to='sales.salestable', verbose_name='Таблица'),
        ),
    ]
