# Generated by Django 4.0.6 on 2023-10-17 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemCourierTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemcourier_table', models.CharField(blank=True, max_length=15, null=True, verbose_name='Хим Курьер')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chemcourier_table', to=settings.AUTH_USER_MODEL, verbose_name='Таблица Хим Курьер')),
            ],
        ),
    ]
