# Generated by Django 4.0.6 on 2023-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
        ('chemcurier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemcouriertablemodel',
            name='chemurier_in_table',
            field=models.ManyToManyField(blank=True, related_name='chemuriers_for_table', to='prices.chemcuriertyresmodel'),
        ),
    ]
