# Generated by Django 4.0.6 on 2023-10-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemcurier', '0002_chemcouriertablemodel_chem_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemcouriertablemodel',
            name='chem_obs',
        ),
    ]
