# Generated by Django 4.0.6 on 2022-10-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPSRussiaFCAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='ТПС РФ FCA')),
                ('date_period', models.DateField(blank=True, verbose_name='период действия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tpsrussiafcacurrency', to='dictionaries.currency')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tpsrussiafcaprice', to='tyres.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='TPSMiddleAsiaFCAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='ТПС Средняя Азия, Закавказье, Молдова FCA')),
                ('date_period', models.DateField(blank=True, verbose_name='период действия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tpsmiddleasiafcacurrency', to='dictionaries.currency')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tpsmiddleasiafcaprice', to='tyres.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='TPSKazFCAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='ТПС Казахстан FCA')),
                ('date_period', models.DateField(blank=True, verbose_name='период действия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tpskazfcacurrency', to='dictionaries.currency')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tpskazfcaprice', to='tyres.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='SemiVariableCosstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='плановая себестоимость')),
                ('date_period', models.DateField(blank=True, verbose_name='период действия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semi_variable_prices_currency', to='dictionaries.currency')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semi_variable_costs', to='tyres.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedCosstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='плановая себестоимость')),
                ('date_period', models.DateField(blank=True, verbose_name='период действия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices_currency', to='dictionaries.currency')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_costs', to='tyres.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='Belarus902PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='прейскуранты №№9, 902')),
                ('date_period', models.DateField(blank=True, verbose_name='период действия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='belarus902currency', to='dictionaries.currency')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='belarus902price', to='tyres.tyre')),
            ],
        ),
    ]
