# Generated by Django 4.0.6 on 2024-05-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='average_price_in_usd',
            field=models.FloatField(blank=True, max_length=30, null=True, verbose_name='средневзвешеная цена, в USD'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='money_on_moth_chem',
            field=models.FloatField(blank=True, max_length=30, null=True, verbose_name='объем поставки на дату(месяц) деньги'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='prod_country',
            field=models.CharField(blank=True, max_length=30, verbose_name='страна производства'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='producer_chem',
            field=models.CharField(max_length=30, verbose_name='производитель химкурьер'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='reciever_chem',
            field=models.CharField(blank=True, max_length=50, verbose_name='получатель химкурьер'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='tyre_size_chem',
            field=models.CharField(max_length=30, verbose_name='типоразмер химкурьер'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistablemodel',
            name='market_table',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='рынок сбыта'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='name_competitor',
            field=models.CharField(blank=True, max_length=35, verbose_name='наименование конкурент'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='parametres_competitor',
            field=models.CharField(blank=True, max_length=35, verbose_name='параметры конкурент'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='site',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='наименование сайта'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='tyresize_competitor',
            field=models.CharField(blank=True, max_length=35, verbose_name='типоразмер конкурент'),
        ),
    ]
