# Generated by Django 4.0.6 on 2022-10-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_comparativeanalysistablemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='planned_costs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_planned_costs', to='prices.plannedcosstmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='semi_variable_prices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_semi_variable_prices', to='prices.semivariablecosstmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpskazfcaprice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_tpskazfcaprice', to='prices.tpskazfcamodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpsmiddleasiafcaprice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_tpsmiddleasiafcaprice', to='prices.tpsmiddleasiafcamodel'),
        ),
        migrations.AlterField(
            model_name='semivariablecosstmodel',
            name='price',
            field=models.FloatField(blank=True, verbose_name='прямые затраты'),
        ),
    ]
