# Generated by Django 4.0.6 on 2024-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_alter_chemcuriertyresmodel_average_price_in_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='average_price_in_usd',
            field=models.FloatField(blank=True, max_length=60, null=True, verbose_name='средневзвешеная цена, в USD'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='money_on_moth_chem',
            field=models.FloatField(blank=True, max_length=60, null=True, verbose_name='объем поставки на дату(месяц) деньги'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='prod_country',
            field=models.CharField(blank=True, max_length=60, verbose_name='страна производства'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='producer_chem',
            field=models.CharField(max_length=60, verbose_name='производитель химкурьер'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='tyre_size_chem',
            field=models.CharField(max_length=60, verbose_name='типоразмер химкурьер'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='name_competitor',
            field=models.CharField(blank=True, max_length=60, verbose_name='наименование конкурент'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='parametres_competitor',
            field=models.CharField(blank=True, max_length=60, verbose_name='параметры конкурент'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='site',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='наименование сайта'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='tyresize_competitor',
            field=models.CharField(blank=True, max_length=60, verbose_name='типоразмер конкурент'),
        ),
    ]
