# Generated by Django 4.0.6 on 2024-09-13 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0003_alter_tyreaddedfeaturemodel_tyre_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionaries', '0003_alter_competitormodel_competitor_name_and_more'),
        ('prices', '0003_alter_chemcuriertyresmodel_average_price_in_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belarus902pricemodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belarus902currency', to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='belarus902pricemodel',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belarus902price', to='tyres.tyre'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='currency_chem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='group_chem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemcurier_group_uusage', to='dictionaries.tyregroupmodel', verbose_name='группа шин'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistablemodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_analysis_table', to=settings.AUTH_USER_MODEL, verbose_name='Таблица сравнительного анализа'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='belarus902price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_belarus902price', to='prices.belarus902pricemodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='currentpricesprice',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_currentpricesprice', to='prices.currentpricesmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='planned_costs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_planned_costs', to='prices.plannedcosstmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='semi_variable_prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_semi_variable_prices', to='prices.semivariablecosstmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpskazfcaprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_tpskazfcaprice', to='prices.tpskazfcamodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpsmiddleasiafcaprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_tpsmiddleasiafcaprice', to='prices.tpsmiddleasiafcamodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpsrussiafcaprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_tpsrussiafcaprice', to='prices.tpsrussiafcamodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_comparative', to='tyres.tyre'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='developer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_competitor', to='dictionaries.competitormodel'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_site_group_uusage', to='dictionaries.tyregroupmodel', verbose_name='группа шин'),
        ),
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_site_sseason_uusage', to='dictionaries.seasonusagemodel', verbose_name='сезонность'),
        ),
        migrations.AlterField(
            model_name='currentpricesmodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentpricescurrency', to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='currentpricesmodel',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentpricesprice', to='tyres.tyre'),
        ),
        migrations.AlterField(
            model_name='datapricevalmoneychemcuriermodel',
            name='price_val_money_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_val_money_data_obj', to='prices.chemcuriertyresmodel', verbose_name='цены, объемы продаж на дату'),
        ),
        migrations.AlterField(
            model_name='plannedcosstmodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_currency', to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='plannedcosstmodel',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_costs', to='tyres.tyre'),
        ),
        migrations.AlterField(
            model_name='semivariablecosstmodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_variable_prices_currency', to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='semivariablecosstmodel',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_variable_costs', to='tyres.tyre'),
        ),
        migrations.AlterField(
            model_name='tpskazfcamodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpskazfcacurrency', to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='tpskazfcamodel',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpskazfcaprice', to='tyres.tyre'),
        ),
        migrations.AlterField(
            model_name='tpsmiddleasiafcamodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpsmiddleasiafcacurrency', to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='tpsmiddleasiafcamodel',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpsmiddleasiafcaprice', to='tyres.tyre'),
        ),
        migrations.AlterField(
            model_name='tpsrussiafcamodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpsrussiafcacurrency', to='dictionaries.currency'),
        ),
        migrations.AlterField(
            model_name='tpsrussiafcamodel',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpsrussiafcaprice', to='tyres.tyre'),
        ),
    ]
