# Generated by Django 4.0.6 on 2022-11-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
        ('dictionaries', '0001_initial'),
        ('prices', '0004_alter_comparativeanalysistyresmodel_belarus902price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPricesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, verbose_name='Действующие цены')),
                ('date_period', models.DateField(blank=True, verbose_name='период действия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currentpricescurrency', to='dictionaries.currency')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currentpricesprice', to='tyres.tyre')),
            ],
        ),
    ]
