# Generated by Django 4.0.6 on 2024-12-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_alter_belarus902pricemodel_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='tyre_to_compare',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='price_tyre_to_compare', to='prices.comparativeanalysistyresmodel'),
        ),
    ]
