# Generated by Django 4.0.6 on 2025-01-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_alter_competitorsitemodel_tyre_to_compare'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCompetitorSiteModelDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(default=dict)),
            ],
        ),
    ]
