# Generated by Django 4.0.6 on 2022-11-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_currentpricesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativeanalysistyresmodel',
            name='currentpricesprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_currentpricesprice', to='prices.tpsmiddleasiafcamodel'),
        ),
    ]
