# Generated by Django 4.0.6 on 2025-01-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_allcompetitorsitemodeldict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcompetitorsitemodeldict',
            old_name='json',
            new_name='chart_one_json',
        ),
    ]
