# Generated by Django 4.0.6 on 2025-01-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_rename_json_allcompetitorsitemodeldict_chart_one_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcompetitorsitemodeldict',
            name='chart_two_json',
            field=models.JSONField(default=dict),
        ),
    ]
