# Generated by Django 4.0.6 on 2022-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_competitorsitemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsitemodel',
            name='competitorname',
            field=models.CharField(blank=True, max_length=25, verbose_name='наименование производитель типоразмер модель'),
        ),
    ]
