# Generated by Django 4.0.6 on 2025-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_allcompetitorsitemodeldict_chart_two_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcompetitorsitemodeldict',
            name='chart_four_json',
            field=models.JSONField(default=dict),
        ),
    ]
