# Generated by Django 4.0.6 on 2022-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_competitorsitemodel_competitorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsitemodel',
            name='developer',
            field=models.CharField(blank=True, max_length=25, verbose_name='производитель'),
        ),
        migrations.AddField(
            model_name='competitorsitemodel',
            name='name_competitor',
            field=models.CharField(blank=True, max_length=25, verbose_name='наименование конкурент'),
        ),
        migrations.AddField(
            model_name='competitorsitemodel',
            name='parametres_competitor',
            field=models.CharField(blank=True, max_length=25, verbose_name='параметры конкурент'),
        ),
        migrations.AddField(
            model_name='competitorsitemodel',
            name='tyresize_competitor',
            field=models.CharField(blank=True, max_length=25, verbose_name='типоразмер конкурент'),
        ),
    ]
