# Generated by Django 4.0.6 on 2022-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0010_competitorsitemodel_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsitemodel',
            name='site',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='наименование сайта'),
        ),
    ]
