# Generated by Django 4.0.6 on 2022-11-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0011_competitorsitemodel_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativeanalysistyresmodel',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_competitor', to='prices.competitorsitemodel'),
        ),
    ]
