# Generated by Django 4.0.6 on 2022-11-28 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0012_comparativeanalysistyresmodel_competitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparativeanalysistyresmodel',
            name='competitor',
        ),
        migrations.AddField(
            model_name='comparativeanalysistyresmodel',
            name='sale_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата парсинга'),
            preserve_default=False,
        ),
    ]
