# Generated by Django 4.0.6 on 2022-11-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0013_remove_comparativeanalysistyresmodel_competitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='belarus902price',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_belarus902price', to='prices.belarus902pricemodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='currentpricesprice',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_currentpricesprice', to='prices.currentpricesmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='semi_variable_prices',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_semi_variable_prices', to='prices.semivariablecosstmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpskazfcaprice',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_tpskazfcaprice', to='prices.tpskazfcamodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpsmiddleasiafcaprice',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_tpsmiddleasiafcaprice', to='prices.tpsmiddleasiafcamodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpsrussiafcaprice',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_tpsrussiafcaprice', to='prices.tpsrussiafcamodel'),
        ),
    ]
