# Generated by Django 4.0.6 on 2022-11-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0014_alter_comparativeanalysistyresmodel_belarus902price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belarus902pricemodel',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='прейскуранты №№9, 902'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='belarus902price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_belarus902price', to='prices.belarus902pricemodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='currentpricesprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_currentpricesprice', to='prices.currentpricesmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='semi_variable_prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_semi_variable_prices', to='prices.semivariablecosstmodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpskazfcaprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_tpskazfcaprice', to='prices.tpskazfcamodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpsmiddleasiafcaprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_tpsmiddleasiafcaprice', to='prices.tpsmiddleasiafcamodel'),
        ),
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='tpsrussiafcaprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_tpsrussiafcaprice', to='prices.tpsrussiafcamodel'),
        ),
        migrations.AlterField(
            model_name='currentpricesmodel',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Действующие цены'),
        ),
        migrations.AlterField(
            model_name='plannedcosstmodel',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='плановая себестоимость'),
        ),
        migrations.AlterField(
            model_name='semivariablecosstmodel',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='прямые затраты'),
        ),
        migrations.AlterField(
            model_name='tpskazfcamodel',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='ТПС Казахстан FCA'),
        ),
        migrations.AlterField(
            model_name='tpsrussiafcamodel',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='ТПС РФ FCA'),
        ),
    ]
