# Generated by Django 4.0.6 on 2022-11-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0015_alter_belarus902pricemodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpsmiddleasiafcamodel',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='ТПС Средняя Азия, Закавказье, Молдова FCA'),
        ),
    ]
