# Generated by Django 4.0.6 on 2022-12-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0017_alter_comparativeanalysistyresmodel_currentpricesprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorsitemodel',
            name='competitorname',
        ),
    ]
