# Generated by Django 4.0.6 on 2022-12-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0018_remove_competitorsitemodel_competitorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorsitemodel',
            name='tyre',
        ),
    ]
