# Generated by Django 4.0.6 on 2022-12-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_rename_contragent_name_competitormodel_competitor_name'),
        ('prices', '0019_remove_competitorsitemodel_tyre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_developer', to='dictionaries.competitormodel', verbose_name='производитель-конкурент'),
        ),
    ]
