# Generated by Django 4.0.6 on 2022-12-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0020_alter_competitorsitemodel_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='developer',
            field=models.CharField(blank=True, default=1, max_length=25, verbose_name='производитель'),
            preserve_default=False,
        ),
    ]
