# Generated by Django 4.0.6 on 2022-12-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_rename_contragent_name_competitormodel_competitor_name'),
        ('prices', '0021_alter_competitorsitemodel_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='developer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='developer_competitor', to='dictionaries.competitormodel'),
        ),
    ]
