# Generated by Django 4.0.6 on 2022-12-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0022_alter_competitorsitemodel_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsitemodel',
            name='tyre_to_compare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_tyre_to_compare', to='prices.comparativeanalysistyresmodel'),
        ),
    ]
