# Generated by Django 4.0.6 on 2022-12-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0023_competitorsitemodel_tyre_to_compare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorsitemodel',
            name='tyre_to_compare',
        ),
        migrations.AddField(
            model_name='competitorsitemodel',
            name='tyre_to_compare',
            field=models.ManyToManyField(blank=True, null=True, related_name='price_tyre_to_compare', to='prices.comparativeanalysistyresmodel'),
        ),
    ]
