# Generated by Django 4.0.6 on 2022-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0025_alter_competitorsitemodel_tyre_to_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsitemodel',
            name='season',
            field=models.CharField(blank=True, max_length=25, verbose_name='сезонность'),
        ),
    ]
