# Generated by Django 4.0.6 on 2022-12-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_studdedusagemodel'),
        ('prices', '0026_competitorsitemodel_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsitemodel',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitor_site_sseason_uusage', to='dictionaries.seasonusagemodel', verbose_name='сезонность'),
        ),
    ]
