# Generated by Django 4.0.6 on 2023-01-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_studdedusagemodel'),
        ('prices', '0027_alter_competitorsitemodel_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemCurierTyresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_size_chem', models.CharField(max_length=10, verbose_name='типоразмер химкурьер')),
                ('producer_chem', models.CharField(max_length=15, verbose_name='производитель химкурьер')),
                ('group_chem', models.CharField(max_length=20, verbose_name='подгруппа химкурьер')),
                ('sale_on_data_month_chem', models.DateTimeField(auto_now_add=True, verbose_name='месяц (дата) поставки шт. / деньги')),
                ('val_on_moth_chem', models.IntegerField(blank=True, verbose_name='объем поставки на дату(месяц) шт.')),
                ('money_on_moth_chem', models.FloatField(blank=True, max_length=20, verbose_name='объем поставки на дату(месяц) деньги')),
                ('price_on_date_chem', models.FloatField(blank=True, max_length=20, verbose_name='цена на дату(месяц) деньги')),
                ('currency_chem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.currency')),
            ],
        ),
    ]
