# Generated by Django 4.0.6 on 2023-01-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0028_chemcuriertyresmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPriceValMoneyChemCurierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_month_chem', models.DateTimeField(auto_now_add=True, verbose_name='месяц (дата) поставки')),
                ('val_on_moth_chem', models.IntegerField(blank=True, verbose_name='объем поставки на дату(месяц) шт.')),
                ('money_on_moth_chem', models.FloatField(blank=True, max_length=20, verbose_name='объем поставки на дату(месяц) деньги')),
                ('price_on_date_chem', models.FloatField(blank=True, max_length=20, verbose_name='цена на дату(месяц) деньги')),
            ],
        ),
        migrations.RemoveField(
            model_name='chemcuriertyresmodel',
            name='money_on_moth_chem',
        ),
        migrations.RemoveField(
            model_name='chemcuriertyresmodel',
            name='price_on_date_chem',
        ),
        migrations.RemoveField(
            model_name='chemcuriertyresmodel',
            name='sale_on_data_month_chem',
        ),
        migrations.RemoveField(
            model_name='chemcuriertyresmodel',
            name='val_on_moth_chem',
        ),
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='price_val_money_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prices.datapricevalmoneychemcuriermodel', verbose_name='цены, объемы продаж на дату'),
        ),
    ]
