# Generated by Django 4.0.6 on 2023-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0030_alter_datapricevalmoneychemcuriermodel_money_on_moth_chem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapricevalmoneychemcuriermodel',
            name='data_month_chem',
            field=models.DateTimeField(verbose_name='месяц (дата) поставки'),
        ),
    ]
