# Generated by Django 4.0.6 on 2023-01-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0031_alter_datapricevalmoneychemcuriermodel_data_month_chem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='price_val_money_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_val_money_data_obj', to='prices.datapricevalmoneychemcuriermodel', verbose_name='цены, объемы продаж на дату'),
        ),
    ]
