# Generated by Django 4.0.6 on 2023-01-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0032_alter_chemcuriertyresmodel_price_val_money_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemcuriertyresmodel',
            name='price_val_money_data',
        ),
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='price_val_money_data',
            field=models.ManyToManyField(blank=True, null=True, related_name='price_val_money_data_obj', to='prices.datapricevalmoneychemcuriermodel', verbose_name='цены, объемы продаж на дату'),
        ),
    ]
