# Generated by Django 4.0.6 on 2023-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0033_remove_chemcuriertyresmodel_price_val_money_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='price_val_money_data',
            field=models.ManyToManyField(blank=True, related_name='price_val_money_data_obj', to='prices.datapricevalmoneychemcuriermodel', verbose_name='цены, объемы продаж на дату'),
        ),
    ]
