# Generated by Django 4.0.6 on 2023-01-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0034_alter_chemcuriertyresmodel_price_val_money_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemcuriertyresmodel',
            name='price_val_money_data',
        ),
        migrations.AddField(
            model_name='datapricevalmoneychemcuriermodel',
            name='price_val_money_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_val_money_data_obj', to='prices.chemcuriertyresmodel', verbose_name='цены, объемы продаж на дату'),
        ),
    ]
