# Generated by Django 4.0.6 on 2023-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0036_alter_competitorsitemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativeanalysistablemodel',
            name='market_table',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='рынок сбыта'),
        ),
    ]
