# Generated by Django 4.0.6 on 2023-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0037_comparativeanalysistablemodel_market_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparativeanalysistyresmodel',
            name='table',
        ),
        migrations.AddField(
            model_name='comparativeanalysistyresmodel',
            name='table',
            field=models.ManyToManyField(blank=True, related_name='comparative_table', to='prices.comparativeanalysistablemodel', verbose_name='Таблица'),
        ),
    ]
