# Generated by Django 4.0.6 on 2023-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0038_remove_comparativeanalysistyresmodel_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='sale_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата парсинга'),
        ),
    ]
