# Generated by Django 4.0.6 on 2023-03-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0039_alter_comparativeanalysistyresmodel_sale_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativeanalysistyresmodel',
            name='sale_data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата парсинга'),
        ),
    ]
