# Generated by Django 4.0.6 on 2023-10-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_studdedusagemodel'),
        ('prices', '0040_alter_comparativeanalysistyresmodel_sale_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsitemodel',
            name='group_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitor_site_group_usage', to='dictionaries.tyregroupmodel', verbose_name='групп шин'),
        ),
    ]
