# Generated by Django 4.0.6 on 2023-10-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_studdedusagemodel'),
        ('prices', '0043_remove_competitorsitemodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsitemodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitor_site_group_uusage', to='dictionaries.tyregroupmodel', verbose_name='группа шин'),
        ),
    ]
