# Generated by Django 4.0.6 on 2023-10-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0044_competitorsitemodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='money_on_moth_chem',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='объем поставки на дату(месяц) деньги'),
        ),
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='val_on_moth_chem',
            field=models.IntegerField(blank=True, null=True, verbose_name='объем поставки на дату(месяц) шт.'),
        ),
    ]
