# Generated by Django 4.0.6 on 2023-10-14 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0045_chemcuriertyresmodel_money_on_moth_chem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='data_month_chem',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='месяц (дата) поставки'),
        ),
    ]
