# Generated by Django 4.0.6 on 2023-10-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0046_chemcuriertyresmodel_data_month_chem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemcuriertyresmodel',
            name='data_month_chem',
            field=models.DateField(auto_now_add=True, verbose_name='месяц (дата) поставки'),
        ),
    ]
