# Generated by Django 4.0.6 on 2023-10-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0048_alter_chemcuriertyresmodel_data_month_chem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='month_counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер месяца.'),
        ),
    ]
