# Generated by Django 4.0.6 on 2023-10-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0049_chemcuriertyresmodel_month_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemcuriertyresmodel',
            name='month_counter',
        ),
    ]
