# Generated by Django 4.0.6 on 2023-10-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0050_remove_chemcuriertyresmodel_month_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='reciever_chem',
            field=models.CharField(blank=True, max_length=25, verbose_name='получатель химкурьер'),
        ),
    ]
