# Generated by Django 4.0.6 on 2023-10-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0051_chemcuriertyresmodel_reciever_chem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='average_price_in_usd',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='средневзвешеная цена, в USD'),
        ),
    ]
