# Generated by Django 4.0.6 on 2023-10-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0056_chemcuriertyresmodel_group_chem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemcuriertyresmodel',
            name='prod_country',
            field=models.CharField(blank=True, max_length=25, verbose_name='страна производства'),
        ),
    ]
