# Generated by Django 4.0.6 on 2022-08-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, verbose_name='валюта')),
            ],
        ),
        migrations.CreateModel(
            name='ModelNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10, verbose_name='модель')),
            ],
        ),
        migrations.CreateModel(
            name='QantityCountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_count', models.CharField(max_length=10, verbose_name='ед. измерения')),
            ],
        ),
        migrations.CreateModel(
            name='TyreGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_group', models.CharField(max_length=10, verbose_name='группа шин')),
            ],
        ),
        migrations.CreateModel(
            name='TyreParametersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_type', models.CharField(max_length=10, verbose_name='параметры шины')),
            ],
        ),
        migrations.CreateModel(
            name='TyreSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_size', models.CharField(max_length=10, verbose_name='типоразмер')),
            ],
        ),
    ]
