# Generated by Django 4.0.6 on 2022-07-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10, verbose_name='модель')),
            ],
        ),
        migrations.CreateModel(
            name='TyreSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_size', models.CharField(max_length=10, verbose_name='типоразмер')),
            ],
        ),
    ]
