# Generated by Django 4.0.6 on 2024-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitormodel',
            name='competitor_name',
            field=models.CharField(max_length=40, verbose_name='наименование производителя-конкурента'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=30, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='modelnamemodel',
            name='model',
            field=models.CharField(max_length=30, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='qantitycountmodel',
            name='quantity_count',
            field=models.CharField(max_length=20, verbose_name='ед. измерения'),
        ),
        migrations.AlterField(
            model_name='seasonusagemodel',
            name='season_usage_name',
            field=models.CharField(max_length=30, verbose_name='сезонность'),
        ),
        migrations.AlterField(
            model_name='studdedusagemodel',
            name='studded_name',
            field=models.CharField(max_length=30, verbose_name='ошиповка'),
        ),
        migrations.AlterField(
            model_name='tyregroupmodel',
            name='tyre_group',
            field=models.CharField(max_length=30, verbose_name='группа шин'),
        ),
        migrations.AlterField(
            model_name='tyreparametersmodel',
            name='tyre_type',
            field=models.CharField(max_length=50, verbose_name='параметры шины'),
        ),
        migrations.AlterField(
            model_name='tyresizemodel',
            name='tyre_size',
            field=models.CharField(max_length=30, verbose_name='типоразмер'),
        ),
    ]
