# Generated by Django 4.0.6 on 2022-12-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contragent_name', models.CharField(max_length=20, verbose_name='наименование производителя-конкурента')),
            ],
        ),
    ]
