# Generated by Django 4.0.6 on 2022-10-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyregroupmodel',
            name='tyre_group',
            field=models.CharField(max_length=15, verbose_name='группа шин'),
        ),
    ]
