# Generated by Django 4.0.6 on 2024-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_alter_competitormodel_competitor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitormodel',
            name='competitor_name',
            field=models.CharField(max_length=80, verbose_name='наименование производителя-конкурента'),
        ),
        migrations.AlterField(
            model_name='contragentsmodel',
            name='contragent_name',
            field=models.CharField(max_length=60, verbose_name='наименование контрагента'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=50, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='modelnamemodel',
            name='model',
            field=models.CharField(max_length=60, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='qantitycountmodel',
            name='quantity_count',
            field=models.CharField(max_length=30, verbose_name='ед. измерения'),
        ),
        migrations.AlterField(
            model_name='seasonusagemodel',
            name='season_usage_name',
            field=models.CharField(max_length=60, verbose_name='сезонность'),
        ),
        migrations.AlterField(
            model_name='studdedusagemodel',
            name='studded_name',
            field=models.CharField(max_length=60, verbose_name='ошиповка'),
        ),
        migrations.AlterField(
            model_name='tyregroupmodel',
            name='tyre_group',
            field=models.CharField(max_length=60, verbose_name='группа шин'),
        ),
    ]
