# Generated by Django 4.0.6 on 2022-12-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_competitormodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitormodel',
            old_name='contragent_name',
            new_name='competitor_name',
        ),
    ]
