# Generated by Django 4.0.6 on 2022-12-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_rename_contragent_name_competitormodel_competitor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonUsageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_usage_name', models.CharField(max_length=20, verbose_name='сезонность')),
            ],
        ),
    ]
