# Generated by Django 4.0.6 on 2022-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_seasonusagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuddedUsageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studded_name', models.CharField(max_length=20, verbose_name='ошиповка')),
            ],
        ),
    ]
