# Generated by Django 4.0.6 on 2022-10-13 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tyres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcxyzTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abcxyz_table', to=settings.AUTH_USER_MODEL, verbose_name='ABCТаблица')),
            ],
        ),
        migrations.CreateModel(
            name='Abcxyz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.ManyToManyField(blank=True, related_name='sales_data', to='sales.sales', verbose_name='продажи')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='abc_table_xyz.abcxyztable', verbose_name='Таблица')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyre_abc', to='tyres.tyre')),
            ],
        ),
    ]
