# Generated by Django 4.0.6 on 2022-09-11 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abc_table_xyz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcxyztable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abcxyz_table', to=settings.AUTH_USER_MODEL, verbose_name='ABCТаблица'),
        ),
    ]
