# Generated by Django 4.0.6 on 2022-08-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('abc_table_xyz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcxyz',
            name='date_of_sales',
        ),
        migrations.RemoveField(
            model_name='abcxyz',
            name='sales_on_date',
        ),
        migrations.RemoveField(
            model_name='abcxyz',
            name='tyre',
        ),
        migrations.AddField(
            model_name='abcxyz',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='sales.sales', verbose_name='продажи'),
        ),
    ]
