# Generated by Django 4.0.6 on 2022-09-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abc_table_xyz', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcxyz',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='sales_data', to='sales.sales', verbose_name='продажи'),
        ),
        migrations.AddField(
            model_name='abcxyz',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='abc_table_xyz.abcxyztable', verbose_name='Таблица'),
        ),
    ]
