# Generated by Django 4.0.6 on 2022-09-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abc_table_xyz', '0002_initial'),
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcxyz',
            name='tyre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyre_abc', to='tyres.tyre'),
        ),
    ]
