# Generated by Django 4.0.6 on 2022-08-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_alter_tyre_tyre_type'),
        ('abc_table_xyz', '0002_remove_abcxyz_date_of_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcxyz',
            name='tyre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_abc', to='tyres.tyre'),
            preserve_default=False,
        ),
    ]
