# Generated by Django 4.0.6 on 2022-08-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('abc_table_xyz', '0007_remove_abcxyz_sales_abcxyz_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcxyz',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='sales_data', to='sales.sales', verbose_name='продажи'),
        ),
    ]
