# Generated by Django 4.0.6 on 2022-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abc_table_xyz', '0008_alter_abcxyz_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcxyz',
            name='sale_date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
