# Generated by Django 4.0.6 on 2022-08-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abc_table_xyz', '0009_abcxyz_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcxyz',
            name='sale_date',
        ),
    ]
