# Generated by Django 4.0.6 on 2024-01-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.CharField(blank=True, max_length=254, unique=True, verbose_name='email'),
        ),
    ]
