# Generated by Django 4.0.6 on 2024-01-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.CharField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
