# Generated by Django 4.0.6 on 2022-09-26 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tire_models', to='dictionaries.modelnamemodel', verbose_name='модель')),
                ('tyre_size', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tire_size', to='dictionaries.tyresizemodel')),
                ('tyre_type', models.ManyToManyField(blank=True, default=None, related_name='tire_parameters', to='dictionaries.tyreparametersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TyreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Серийное освоение')),
                ('picture', models.ImageField(upload_to='books/%Y/%m/%d/', verbose_name='картинка')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyre_card', to='tyres.tyre')),
            ],
        ),
    ]
