# Generated by Django 4.0.6 on 2023-10-17 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_group', models.ManyToManyField(blank=True, default=None, related_name='tire_group', to='dictionaries.tyregroupmodel')),
                ('tyre_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tire_models', to='dictionaries.modelnamemodel', verbose_name='модель')),
                ('tyre_size', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tire_size', to='dictionaries.tyresizemodel')),
                ('tyre_type', models.ManyToManyField(blank=True, default=None, related_name='tire_parameters', to='dictionaries.tyreparametersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TyreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Серийное освоение')),
                ('picture', models.ImageField(upload_to='books/%Y/%m/%d/', verbose_name='картинка')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyre_card', to='tyres.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='TyreAddedFeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexes_list', models.CharField(max_length=30, null=True, verbose_name='список индексов')),
                ('tyre_thread', models.CharField(max_length=15, null=True, verbose_name='рисунок протектора')),
                ('ax', models.CharField(max_length=15, null=True, verbose_name='ось')),
                ('usability', models.CharField(max_length=15, null=True, verbose_name='применяемость')),
                ('season_usage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitor_sseason_uusage', to='dictionaries.seasonusagemodel')),
                ('studded_usage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitor_studded_uusage', to='dictionaries.studdedusagemodel')),
                ('tyre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_features', to='tyres.tyre', verbose_name='дополнительные данные о шине')),
            ],
        ),
    ]
