# Generated by Django 4.0.6 on 2022-07-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='исполнение')),
                ('prime_cost', models.FloatField(blank=True, null=True, verbose_name='полные затраты')),
                ('direct_costs', models.FloatField(blank=True, null=True, verbose_name='прямые затраты')),
                ('currency', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tyre_currency', to='dictionaries.currency', verbose_name='валюта')),
                ('tyre_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tire_models', to='dictionaries.modelnamemodel')),
                ('tyre_size', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tire_size', to='dictionaries.tyresizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TyreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_date', models.DateField(blank=True, verbose_name='Серийное освоение')),
                ('picture', models.ImageField(upload_to='books/%Y/%m/%d/', verbose_name='картинка')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyre_card', to='tyres.tyre')),
            ],
        ),
    ]
