# Generated by Django 4.0.6 on 2024-05-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyreaddedfeaturemodel',
            name='ax',
            field=models.CharField(max_length=50, null=True, verbose_name='ось'),
        ),
        migrations.AlterField(
            model_name='tyreaddedfeaturemodel',
            name='usability',
            field=models.CharField(max_length=50, null=True, verbose_name='применяемость'),
        ),
    ]
