# Generated by Django 4.0.6 on 2022-08-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='tyre_type',
            field=models.ManyToManyField(blank=True, default=None, related_name='tire_parameters', to='dictionaries.tyreparametersmodel'),
        ),
    ]
