# Generated by Django 4.0.6 on 2022-10-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='tyre_group',
            field=models.ManyToManyField(blank=True, default=None, related_name='tire_group', to='dictionaries.tyregroupmodel'),
        ),
    ]
