# Generated by Django 4.0.6 on 2022-07-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_alter_tyre_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyre',
            name='currency',
        ),
    ]
