# Generated by Django 4.0.6 on 2022-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_tyreaddedfeaturemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyreaddedfeaturemodel',
            name='ax',
            field=models.CharField(max_length=15, null=True, verbose_name='ось'),
        ),
        migrations.AlterField(
            model_name='tyreaddedfeaturemodel',
            name='indexes_list',
            field=models.CharField(max_length=30, null=True, verbose_name='список индексов'),
        ),
        migrations.AlterField(
            model_name='tyreaddedfeaturemodel',
            name='season_usage',
            field=models.CharField(max_length=15, null=True, verbose_name='сезонность'),
        ),
        migrations.AlterField(
            model_name='tyreaddedfeaturemodel',
            name='tyre_thread',
            field=models.CharField(max_length=15, null=True, verbose_name='рисунок протектора'),
        ),
        migrations.AlterField(
            model_name='tyreaddedfeaturemodel',
            name='usability',
            field=models.CharField(max_length=15, null=True, verbose_name='применяемость'),
        ),
    ]
