# Generated by Django 4.0.6 on 2024-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0003_alter_tyreaddedfeaturemodel_tyre_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreaddedfeaturemodel',
            name='line_in_excel',
            field=models.FloatField(max_length=6, null=True, verbose_name='строка для отличия одинаковых'),
        ),
    ]
