# Generated by Django 4.0.6 on 2022-12-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_studdedusagemodel'),
        ('tyres', '0003_alter_tyreaddedfeaturemodel_ax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyreaddedfeaturemodel',
            name='season_usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitor_sseaon_uusage', to='dictionaries.seasonusagemodel'),
        ),
    ]
