# Generated by Django 4.0.6 on 2024-11-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0004_tyreaddedfeaturemodel_line_in_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyreaddedfeaturemodel',
            name='line_in_excel',
        ),
        migrations.AddField(
            model_name='tyre',
            name='line_in_excel',
            field=models.FloatField(max_length=6, null=True, verbose_name='строка для отличия одинаковых'),
        ),
    ]
