# Generated by Django 4.0.6 on 2024-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0005_remove_tyreaddedfeaturemodel_line_in_excel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='line_in_excel',
            field=models.FloatField(max_length=6, null=True, verbose_name='строка в excel'),
        ),
    ]
