# Generated by Django 4.0.6 on 2022-09-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abcxyz_group', models.CharField(max_length=5, verbose_name='abc_xyz_group')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyres_home', to='tyres.tyre')),
            ],
        ),
    ]
