# Generated by Django 4.0.6 on 2022-10-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
        ('homepage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre_Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_home', to='homepage.homepagemodel', verbose_name='Таблица главная')),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tyr_homepage', to='tyres.tyre')),
            ],
        ),
    ]
